#!/usr/bin/python 

"""
The Python Imlac emulator (pymlac).

Console-only version
"""

import sys
import getopt

from Globals import *
import Imlac
import Trace


def handle_options():
    """Routine to analyse command line options.

    Sets globals to input values.
    """

    global boot_rom
    global loadfile
    global corefile
    global tracing
    global tracestart
    global traceend
    global run_address

    try:
        opts, pargs = getopt.gnu_getopt(sys.argv[1:], 'b:chr:t:?')
    except getopt.GetoptError, e:
        print e, '\n'
        usage()

    errors= 0

    for opt, arg in opts:
        if opt == "-b":
            if arg == 'ptr':
                boot_rom = ROM_PTR
            elif arg == 'tty':
                boot_rom = ROM_TTY
            else:
                print "'-b' option must be followed by 'ptr' or 'tty'"
                errors = 1
        elif opt == "-c":
            corefile = None
        elif opt == '-h':
            usage()
        elif opt == '-r':
            if len(arg) <= 0:
                print "'-r' must be followed by a run address in octal"
                errors = 1
            else:
                if run_address == None:
                    try:
                        run_address = int(arg, 8)
                    except:
                        print "'-r' must be followed by a run address in octal"
                        errors = 1
                else:
                    print "there can be only one '-r' option"
                    errors = 1
        elif opt == '-t':
            splitarg = arg.split(',')
            if len(splitarg) == 1:
                tracestart = int(splitarg[0], 8)
            elif len(splitarg) == 2:
                tracestart = int(splitarg[0], 8)
                traceend = int(splitarg[1], 8)
            else:
                print "'-t' must be followed by 1 or 2 addresses"
                errors = 1
        elif opt == "-?":
            usage()

    if len(pargs) > 1:
        print 'only one file may be specified'
        errors = 1

    if errors:
        print ''
        usage()

    if len(pargs) > 0:
        loadfile = pargs[0]


def syserror(msg):
    """Report a system error."""

    print msg
    sys.exit()


def usage():
    """Help for befuddled user."""

    print('Usage:\n')
    print('pymlac [-b (ptr|tty)] [-c] [-t [<a>[,<b>]]] [<imlacfile>] [-r <address>]\n')
    print('where -b [ptr|tty]           sets the bootstrap ROM code, if no device disable ROM')
    print('      -c                     clear core, except bootstrap ROM')
    print('      -h                     prints this help')
    print('      -r [<address>]         execute from the <address>, no address runs from current PC')
    print('      -s <setfile>           sets memory values from file')
    print('      -t [<addr1>[,<addr2>]] controls trace:')
    print('                               -t 100     trace from address 0100')
    print('                               -t 100,200 traces between addresses 100 and 200')
    print('                             if no addresses given, trace from next instruction')
    print('      -v <viewfile>          prints memory locations from file')
    print('and   <imlacfile>            is a file to mount on the input device (ptr or tty)')
    sys.exit()


# set defaults
boot_rom = ROM_PTR
run_address = None
loadfile = None
corefile = CORE_FILENAME
tracing = False
tracestart = None
traceend = None


def main():
    """Start of the Imlac emulator."""

    global boot_rom
    global loadfile
    global corefile
    global tracing
    global tracestart
    global traceend
    global run_address

    handle_options()

    ######
    # Initialize the emulator.
    ######

    imlac = Imlac.Imlac(run_address, TRACE_FILENAME, tracestart,
                        traceend, boot_rom, corefile)

    # mount the file, if it was specified
    if loadfile:
        try:
            if boot_rom == ROM_PTR:
                imlac.ptr_mount(loadfile)
            else:
                imlac.ttyin_mount(loadfile)
        except IOError, e:
            print e
            sys.exit()

    while True:
        if imlac.execute_once() == 0:
            break

    imlac.close(corefile)

#import profile
#profile.run('main()', 'profile.out')

main()
