#
# Run the program
#

all:
	python skyline.py 5.dat
	python skyline.py 9.dat
	python skyline.py 99.dat
	python skyline.py 999.dat
	python skyline.py 9999.dat
	python skyline.py 99999.dat
	python skyline.py 999999.dat

clean:
	rm -f *.pyc
